In [21]:
import pandas as pd
import mysql.connector
from datetime import datetime

# Step 1: Load Data
file_path = r"C:\Users\Digital Suppliers\Desktop\Projects of Mine\police\Police_Dataset - file.csv"
df = pd.read_csv(file_path)

In [22]:
df

,stop_date,stop_time,country_name,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop
0,1/2/2005,1:55,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
1,1/18/2005,8:15,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
2,1/23/2005,23:15,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
3,2/20/2005,17:15,NaN,M,1986.0,19.0,White,Call for Service,Other,False,NaN,Arrest Driver,True,16-30 Min,False
4,3/14/2005,10:00,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65530,12/6/2012,17:54,NaN,F,1987.0,25.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False
65531,12/6/2012,22:22,NaN,M,1954.0,58.0,White,Speeding,Speeding,False,NaN,Warning,False,0-15 Min,False
65532,12/6/2012,23:20,NaN,M,1985.0,27.0,Black,Equipment/Inspection Violation,Equipment,False,NaN,Citation,False,0-15 Min,False
65533,12/7/2012,0:23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,False
65534,12/7/2012,0:30,NaN,F,1985.0,27.0,White,Speeding,Speeding,False,NaN,Citation,False,0-15 Min,False

In [23]:
# Step 2: Data Cleaning
# Drop columns with all missing values
df.dropna(axis=1, how='all', inplace=True)

# Fill NaNs with suitable values
df.fillna({
    'driver_age': df['driver_age'].median(),
    'search_type': 'None',
    'stop_duration': 'Unknown',
    'violation': 'Unknown',
    'stop_outcome': 'Unknown',
}, inplace=True)

# Convert date & time to timestamp
df['timestamp'] = pd.to_datetime(df['stop_date'] + ' ' + df['stop_time'])

In [2]:
import pymysql

In [4]:
# Connect to MySQL
conn = pymysql.connect(
    host="localhost",
    user="root",
    password="1234",
 
)

cursor = conn.cursor()
cursor.execute("create database securecheck")

1

In [8]:

cursor.execute("USE securecheck;")

0

In [17]:
cursor.execute("""CREATE TABLE IF NOT EXISTS police_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    stop_date DATE,
    stop_time TIME,
    county_name VARCHAR(100),
    driver_gender VARCHAR(10),
    driver_age INT,
    driver_race VARCHAR(50),
    violation VARCHAR(100),
    search_conducted BOOLEAN,
    search_type VARCHAR(100),
    stop_outcome VARCHAR(100),
    drugs_related_stop BOOLEAN,
    stop_duration VARCHAR(50),
    vehicle_number VARCHAR(50),
    timestamp DATETIME
)""")

0

In [24]:

# Data Cleaning
df.dropna(axis=1, how='all', inplace=True)

df.fillna({
    'driver_age': df['driver_age'].median(),
    'search_type': 'None',
    'stop_duration': 'Unknown',
    'violation': 'Unknown',
    'stop_outcome': 'Unknown',
}, inplace=True)

# Create Timestamp column
df['timestamp'] = pd.to_datetime(df['stop_date'] + ' ' + df['stop_time'])

In [25]:
df

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,timestamp
0,1/2/2005,1:55,M,1985.0,20.0,White,Speeding,Speeding,False,None,Citation,False,0-15 Min,False,2005-01-02 01:55:00
1,1/18/2005,8:15,M,1965.0,40.0,White,Speeding,Speeding,False,None,Citation,False,0-15 Min,False,2005-01-18 08:15:00
2,1/23/2005,23:15,M,1972.0,33.0,White,Speeding,Speeding,False,None,Citation,False,0-15 Min,False,2005-01-23 23:15:00
3,2/20/2005,17:15,M,1986.0,19.0,White,Call for Service,Other,False,None,Arrest Driver,True,16-30 Min,False,2005-02-20 17:15:00
4,3/14/2005,10:00,F,1984.0,21.0,White,Speeding,Speeding,False,None,Citation,False,0-15 Min,False,2005-03-14 10:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65530,12/6/2012,17:54,F,1987.0,25.0,White,Speeding,Speeding,False,None,Citation,False,0-15 Min,False,2012-12-06 17:54:00
65531,12/6/2012,22:22,M,1954.0,58.0,White,Speeding,Speeding,False,None,Warning,False,0-15 Min,False,2012-12-06 22:22:00
65532,12/6/2012,23:20,M,1985.0,27.0,Black,Equipment/Inspection Violation,Equipment,False,None,Citation,False,0-15 Min,False,2012-12-06 23:20:00
65533,12/7/2012,0:23,NaN,NaN,31.0,NaN,NaN,Unknown,False,None,Unknown,NaN,Unknown,False,2012-12-07 00:23:00
65534,12/7/2012,0:30,F,1985.0,27.0,White,Speeding,Speeding,False,None,Citation,False,0-15 Min,False,2012-12-07 00:30:00

In [27]:
# Convert stop_date to correct format (YYYY-MM-DD)
df['stop_date'] = pd.to_datetime(df['stop_date'], errors='coerce').dt.strftime('%Y-%m-%d')

# Also make sure stop_time is in correct format (HH:MM:SS)
df['stop_time'] = pd.to_datetime(df['stop_time'], format='%H:%M:%S', errors='coerce').dt.strftime('%H:%M:%S')

In [28]:
df

,stop_date,stop_time,driver_gender,driver_age_raw,driver_age,driver_race,violation_raw,violation,search_conducted,search_type,stop_outcome,is_arrested,stop_duration,drugs_related_stop,timestamp
0,2005-01-02,NaN,M,1985.0,20.0,White,Speeding,Speeding,False,None,Citation,False,0-15 Min,False,2005-01-02 01:55:00
1,2005-01-18,NaN,M,1965.0,40.0,White,Speeding,Speeding,False,None,Citation,False,0-15 Min,False,2005-01-18 08:15:00
2,2005-01-23,NaN,M,1972.0,33.0,White,Speeding,Speeding,False,None,Citation,False,0-15 Min,False,2005-01-23 23:15:00
3,2005-02-20,NaN,M,1986.0,19.0,White,Call for Service,Other,False,None,Arrest Driver,True,16-30 Min,False,2005-02-20 17:15:00
4,2005-03-14,NaN,F,1984.0,21.0,White,Speeding,Speeding,False,None,Citation,False,0-15 Min,False,2005-03-14 10:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65530,2012-12-06,NaN,F,1987.0,25.0,White,Speeding,Speeding,False,None,Citation,False,0-15 Min,False,2012-12-06 17:54:00
65531,2012-12-06,NaN,M,1954.0,58.0,White,Speeding,Speeding,False,None,Warning,False,0-15 Min,False,2012-12-06 22:22:00
65532,2012-12-06,NaN,M,1985.0,27.0,Black,Equipment/Inspection Violation,Equipment,False,None,Citation,False,0-15 Min,False,2012-12-06 23:20:00
65533,2012-12-07,NaN,NaN,NaN,31.0,NaN,NaN,Unknown,False,None,Unknown,NaN,Unknown,False,2012-12-07 00:23:00
65534,2012-12-07,NaN,F,1985.0,27.0,White,Speeding,Speeding,False,None,Citation,False,0-15 Min,False,2012-12-07 00:30:00

In [30]:
df = df.where(pd.notnull(df), None)

In [31]:
# Convert stop_date and stop_time to proper formats
df['stop_date'] = pd.to_datetime(df['stop_date'], errors='coerce').dt.strftime('%Y-%m-%d')
df['stop_time'] = pd.to_datetime(df['stop_time'], errors='coerce').dt.strftime('%H:%M:%S')

# Replace NaN with None
df = df.where(pd.notnull(df), None)

# Prepare Insert Query
insert_query = """
    INSERT INTO police_logs (
        stop_date, stop_time, county_name, driver_gender, driver_age, driver_race,
        violation, search_conducted, search_type, stop_outcome,
        drugs_related_stop, stop_duration, vehicle_number, timestamp
    ) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

# Iterate DataFrame and Insert Rows
for _, row in df.iterrows():
    cursor.execute(insert_query, (
        row['stop_date'],
        row['stop_time'],
        row.get('county_name'),
        row.get('driver_gender'),
        int(row.get('driver_age')) if row.get('driver_age') is not None else None,
        row.get('driver_race'),
        row.get('violation'),
        bool(row.get('search_conducted')) if row.get('search_conducted') is not None else None,
        row.get('search_type'),
        row.get('stop_outcome'),
        bool(row.get('drugs_related_stop')) if row.get('drugs_related_stop') is not None else None,
        row.get('stop_duration'),
        row.get('vehicle_number', f'VEH{row.name}'),
        row['timestamp']
    ))

# Commit and Close Connection
conn.commit()
cursor.close()
conn.close()

print("Data inserted successfully into single table!")

Data inserted successfully into single table!